### ISSUE TITLE
consider including metadata/tagging feature?

### ISSUE THREAD

**Issue by jrochkind** [grosser/maxitest#10]
The one feature I always wanted that is not in here is test 'tagging', as in:

    it "something", some_tag: "something" do

(Or I suppose you could do that in test-unit-style do as `def something_test(some_tag => 'something')`, although I never have). 

It is useful for things like:

   * tagging certain tests to be automatically wrapped by [vcr](https://github.com/vcr/vcr) setup/teardown (typical vcr rspec usage pattern)
   * tagging certain tests to use capybara javascript driver setup/teardown (typical capybara rspec usage pattern)
   * whatever other custom behavior you want, once you have tests/examples tagged, it's easy to write your own before/after/around's that do certain things with certain tags. 

Here's one existing implementations of adding metadata/tagging to minitest, I'm not sure how robustly or cleanly it's written. 

https://github.com/wojtekmach/minitest-metadata

As metadata-tags are a feature you can then use to build other things, having a particular implementation 'blessed' by the maxitest extension project would be useful to establish common ground to build these other things, with some degree of support expectation etc.

**Comment by grosser** [comment]
I like metadata, but I think it's a fairly uncommon usecase ... and lots of it can be done via normal things like having a dedicated block for vcr or a it_with_vcr ... or mixing in modules to the baseclass of the controller tests ... I can see it being somewhat useful, but on the other hand it's another hack that needs to wrap all test blocks which is not very nice ...

**Comment by jrochkind** [comment]
Okay, thanks for the response. 

It is a pretty common use case with rspec, the recommended configuration for both Capybara and VCR (both very popular gems) is to use metadata tags with rspec.

**Comment by grosser** [comment]
But they won't recommend it for minitest since maxitest is just a tiny fraction of that userbase ...
Maybe have readme docs on how to get metadata / tagging working ?
