### ISSUE TITLE
Maxitest may interfere with other reporters?

### ISSUE THREAD

**Issue by icantrap** [grosser/maxitest#18]
I'm having an issue using maxitest in conjunction with minitest-reporters. It appears that using both causes minitest-reporters to not work correctly. When using their RubyMine reporter, exceptions occur.

I created a minimal project to demonstrate this at https://github.com/icantrap/maxitest-sample. Have you guys seen something similar with other custom minitest reporters?

**Comment by grosser** [comment]
never used it with other reporters ... try bundle open maxitest and just
comment out things until you find what causes it ...

**Comment by icantrap** [comment]
Thanks for the quick response ...

If I comment out the inclusion of `maxitest/verbose_backtrace` and `maxitest/vendor/line`, everything works fine together.

**Comment by grosser** [comment]
... yeah adding any kind of plugin breaks it :/

```
require 'minitest/autorun'
require 'minitest/reporters'
Minitest.extensions << "rg"
```

... so complain with Rubymine folks ... minitest-reporters ...

**Comment by grosser** [comment]
alternatively detect rubymine and sqitch from maxitest to minitest + selected maxitest parts you need
