### ISSUE TITLE
`mtest --help` doesn't

### ISSUE THREAD

**Issue by mperham** [grosser/maxitest#41]
I was trying to figure out how to invoke `mtest`.

```
% bundle exec mtest --help   
ruby -rbundler/setup --help -e 
Usage: ruby [switches] [--] [programfile] [arguments]
```

**Comment by grosser** [comment]
yeah it's basically `mtest file_test.rb` or `mtest file_test.rb:123` ... but needs a fix 👍

**Comment by grosser** [comment]
4.3.0

**Comment by mperham** [comment]
Thank you so much for Maxitest! I switched the Sidekiq test suite over to use it and it’s been fantastic. I used the thread feature to find a racy test which had been plaguing me for months now. I owe you big!

**Comment by grosser** [comment]
Glad you found it useful 😄
