### ISSUE TITLE
Check for leaked processes and file descriptors

### ISSUE THREAD

**Issue by fatkodima** [grosser/maxitest#45]
The existing check for [leaked threads](https://github.com/grosser/maxitest/blob/master/lib/maxitest/threads.rb) is very useful.
It is also a common mistake to forget to close opened file descriptors or join forked processes. Wdyt about adding such checks?
Processes are not as much a popular problem, as file descriptors. 

I made a little investigation on how to get the list of those prior to opening this issues. Unfortunately, it is not as easy as to get the list of threads 😅 And we need to care to not introduce a performance hit, since these will be run before and after each test case. I propose some of the "solutions", but maybe you know how to do it better.

To get the list of opened file descriptors, we can:
1. Run something like `ObjectSpace.each_object(IO) { ... }` 
2. Monkey patch `File#open`/`File#close` to track fds.
3. Run some unix command like `lsof`
4. Iterate over some max number (100, for example) and check if it is a valid fd

To get the list of child processes:
1. Monkey patching `fork`/`join`/etc
2. Run some unix command like `ps`/`pgrep`, query `/proc` file system

**Comment by grosser** [comment]
prefer unix commands and ObjectSpace
since that would be opt-in like the thread monitoring it does not matter if it's a bit slow, as long as it's not super-slow
I rarely ended up needing this, so another approach would be to build this logic in the app you are needing it unless the idea is to reuse this in multiple apps

**Comment by fatkodima** [comment]
> I rarely ended up needing this

Yes, me too, but having such checks enabled (or enable the once in a while to check for some problems) can help avoiding flaky tests (if these threads were created in the test code), which may be introduced by not freed resource somehow. A recent example of this https://github.com/sidekiq/sidekiq/pull/5779 - I hacked some tracking code to actually identify what the problem is, but would benefit from such a solution built-in into `maxitest`. Or some errors waiting to happen on production (like an error to allocate a thread or opened fds limit).

> so another approach would be to build this logic in the app you are needing it unless the idea is to reuse this in multiple apps

Yes, it can for sure be used many times on multiple apps. So if you are open for such change, I can try to work on a PR, otherwise I can for sure just implement it into my app.

**Comment by grosser** [comment]
PR welcome, as long as the logic is opt-in :)

**Comment by fatkodima** [comment]
Ok, made a sketch of the feature for file descriptors and tested it locally - lots of false positives, because of the lazily created sockets for connections in connection pools, lazily created loggers etc. 

There would be possibly less false positives for processes, but these are rarely created in tests too.
So, imo, this feature is not worth it.
