### ISSUE TITLE
Drop support for legacy minitest and rubies

### ISSUE THREAD

**Issue by seuros** [grosser/maxitest#48]
I propose that we refactor the codebase by dropping support for EOL rubies and minitest. This move will simplify the maintenance efforts and make test more robust.

Users on other hand can upgrade their gems or rubies to benefit from all the new things we add.

We will avoid doing conditions like : https://github.com/grosser/maxitest/blob/master/lib/maxitest/threads.rb#L3

wdyt ?

**Comment by grosser** [comment]
yeah let's drop a few EOL versions and wait if/how many complain about
issues :)

**Comment by seuros** [comment]
I don't think anyone will complain!  
they don't even upgrade minitest, you think they will upgrade maxitest or even open an issue ?

**Comment by Nakilon** [comment]
> I don't think anyone will complain!

I wonder (no I don't) how people even get to this idea.

I now have to dive into commits to find the one before the version dump just to test the testrbl hotfix... And then needlessly git clone the fork to force push the rebased version.

**Comment by grosser** [comment]
we also can't support every edge-case forever

The correct wording would have been "I think the chance of complaints is low"
and that was correct, it took 1y for anyone to complain 🤷 

can you help us understand your use-case, why run a EOL version of ruby/minitest ?
