### ISSUE TITLE
Some sort of changelog?

### ISSUE THREAD

**Issue by mperham** [grosser/maxitest#51]
I picked up 5.0 this morning but can't find any documentation about what changed. Can you provide a changes.md, a milestone in GitHub Issues, or some other summary of what users might need to know about the upgrade? For instance, Sidekiq 7 supports Ruby 2.7 but maxitest 5.0 appears to be `>= 3` only so I can't use 5.x.

**Comment by grosser** [comment]
the version bum is only dropping ruby 2.7
I'll get a changelog started soon

**Comment by grosser** [comment]
done
