### ISSUE TITLE
before :all / after :all / around :all support

### ISSUE THREAD

**Issue by jeremyevans** [grosser/maxitest#7]
This is mentioned in the TODO in the README.  You may want to look into integrating minitest-hooks (https://github.com/jeremyevans/minitest-hooks) instead of minitest-around, as minitest-hooks has support for before :all / after :all / around :all hooks, as well as around hooks, and doesn't implement around via Fiber hacks.

**Comment by splattael** [comment]
`minitest-hooks` looks really nice! :)

Does it support the spec version of `around`? On https://github.com/jeremyevans/minitest-hooks/blob/master/spec/minitest_hooks_spec.rb#L25 `def around` is used which is not very spec-like, isn't?

**Comment by jeremyevans** [comment]
I can add support for the spec version of around/around(:all) to minitest-hooks.  It can get a little tricky to use though, because you need to use define_method, and super/yield semantics are different inside define_method methods compared to normally defined methods.

But this will give people the option to use the DSL version and avoid defining the method manually.

**Comment by grosser** [comment]
This around/all problem is pretty nasty, so I have my doubts that minitest-hooks passes all the tests of minitest-around and all the tests in my try on implementing before/after-all hooks https://github.com/grosser/maxitest/pull/5

If you get minitest-around test-suite to run with minitest-hooks I'm all in favor of switching it though :)

**Comment by jeremyevans** [comment]
I've pushed out a 1.1.0 release of minitest-hooks that adds support for block-based around/around(:all) hooks:

```ruby
  around(:all) do |&block|
    DB.transaction(:rollback=>:always){super(&block)}
  end

  around do |&block|
    DB.transaction(:rollback=>:always, :savepoint=>true, :auto_savepoint=>true){super(&block)}
  end
```

@grosser Have you looked at the minitest-hooks implementation and specs?  I checked and it does pass the before/after all specs from #5 (I removed the `order_dependent!` call as that isn't in standard minitest), here's the test output:

```
BEFORE ALL A -- from let
BEFORE A -- true
AFTER A
.BEFORE A -- true
AFTER A
.AFTER ALL A -- from let
BEFORE ALL A -- from let
BEFORE ALL B -- from let
BEFORE A -- true
BEFORE B -- true
AFTER B
AFTER A
.BEFORE A -- true
BEFORE B -- true
AFTER B
AFTER A
.AFTER ALL B -- from let
AFTER ALL A -- from let
```

minitest-hooks has a different API than minitest-around, since minitest-around passes an argument that you have to call, while minitest-hooks just defines a method that allows you to call super.  So I couldn't test directly with minitest-around specs.  But if you come across something that doesn't work, please open an issue in minitest-hooks.

**Comment by splattael** [comment]
@jeremyevans Great work! Let me see if I can run RSpec based fixtures from minttest-around.
If they pass I happily switch to minutest-hooks and abandon mine :)

**Comment by grosser** [comment]
the around seems to be working with some minor ordering issues

https://github.com/jeremyevans/minitest-hooks/pull/1

**Comment by grosser** [comment]
please check out: https://github.com/grosser/maxitest/pull/8

 - no Fibers
 - minitest-around / rspec syntax
 - multiple around/before/after per class
 - no before/after :all since they are redone before and after each subclass which is misleading ... use let_all for reliable global state 
 - around is run before everything, does not maintain order of before and afters ... that puts us back to exactly where minitest-around was before the refactor to fibers, right ? https://github.com/splattael/minitest-around/pull/11

**Comment by grosser** [comment]
and another one ... this time replacing around with hooks + making it play nice with multiple blocks and not needing to include it by hand

https://github.com/grosser/maxitest/pull/9

**Comment by grosser** [comment]
reopening since this would still be nice to have

**Comment by grosser** [comment]
adding `before :all` since that was easy
blocking after :all / around :all since they are traps from minitest atm

https://github.com/grosser/maxitest/pull/53

**Comment by grosser** [comment]
created new issue for `after :all` and `around :all`
https://github.com/grosser/maxitest/issues/54
