### ISSUE TITLE
Minitest reporter SystemStackError with the trap extension

### ISSUE THREAD

**Issue by seuros** [grosser/maxitest#71]
When adding 'gem 'minitest-reporters''  i get  `respond_to?': stack level too deep (SystemStackError) ??:??:??

I located the error in Maxitest::InterruptHandler.  

Is there a way to disable the trap ?

**Comment by grosser** [comment]
I'm using minitest-reporters with maxitest in a few projects and never ran into that, not sure how to reproduce this,
your solution also disables all other maxitest features right <-> might as well remove the gem ?

**Comment by seuros** [comment]
No, i just have the autorun copied in my test_helper except https://github.com/grosser/maxitest/blob/master/lib/maxitest/autorun.rb#L4

**Comment by grosser** [comment]
Can you reproduce the error in a small example app, don't want ppl copy
pasting the whole file 😸

**Comment by seuros** [comment]
Yes !

**Comment by grosser** [comment]
issue seems to be conflict with `Minitest::Reporters.use!`
```
	from minitest-reporters-1.7.1/lib/minitest/reporters.rb:47:in `run_with_hooks'
	from maxitest-5.7.0/lib/maxitest/trap.rb:27:in `run'
```
one using alias_method_chain and other user prepend 😞 

https://github.com/minitest-reporters/minitest-reporters/pull/357 to fix in minitest-reporters
confirmed working by using `gem 'minitest-reporters', path: "~/Code/tools/minitest-reporters"` in Gemfile

https://github.com/grosser/maxitest/pull/72 to fix the issue now, add `ENV["MAXITEST_NO_INTERRUPT"] = "true"` before require maxitest/autorun

**Comment by grosser** [comment]
5.7.1
