### ISSUE TITLE
Improve Output Format for Failing Tests in Maxitest

### ISSUE THREAD

**Issue by seuros** [grosser/maxitest#73]
When running Maxitest, the current output format for failing tests looks like this:

```bash
Focus on failing tests:
mtest test/controllers/interna_test.rb:41
```
It would be more helpful if the output included the full command to re-run the test, like so:

```bash
Focus on failing tests:
bin/rails test test/controllers/interna_test.rb:41
```

This would make it easier to quickly re-run failing tests without manually modifying the command.

**Comment by grosser** [comment]
`mtest test/controllers/interna_test.rb:41` is supposed to work too, but is broken because of https://github.com/minitest/minitest-rails/issues/256
... I guess we could add a "use bin/rails" if "bin/rails" exists check to circumvent that

**Comment by grosser** [comment]
should not be an issue, https://github.com/grosser/maxitest/blob/master/Rakefile#L16 this modifies the vendored code

**Comment by grosser** [comment]
https://github.com/grosser/maxitest/pull/74 -> 5.8.0

**Comment by seuros** [comment]
Thanks
